const types = {
  GET_BANNERS: "GET_BANNERS",
  GET_BANNERS_SUCCESS: "GET_BANNERS_SUCCESS",
  GET_BANNERS_FAILED: "GET_BANNERS_FAILED",

  GET_ALL_BANNERS: "GET_ALL_BANNERS",
  GET_ALL_BANNERS_SUCCESS: "GET_ALL_BANNERS_SUCCESS",
  GET_ALL_BANNERS_FAILED: "GET_ALL_BANNERS_FAILED",
  
  CREATE_BANNER: "CREATE_BANNER",
  CREATE_BANNER_SUCCESS: "CREATE_BANNER_SUCCESS",
  CREATE_BANNER_FAILED: "CREATE_BANNER_FAILED",

  UPDATE_BANNER: "UPDATE_BANNER",
  UPDATE_BANNER_SUCCESS: "UPDATE_BANNER_SUCCESS",
  UPDATE_BANNER_FAILED: "UPDATE_BANNER_FAILED",

  DELETE_BANNER: "DELETE_BANNER",
  DELETE_BANNER_SUCCESS: "DELETE_BANNER_SUCCESS",
  DELETE_BANNER_FAILED: "DELETE_BANNER_FAILED",
}

export default types;
