const types = {
  UPDATE_USER: "UPDATE_USER",
  
  UPDATE_ACCOUNT: "UPDATE_ACCOUNT",
  UPDATE_ACCOUNT_SUCCESS: "UPDATE_ACCOUNT_SUCCESS",
  UPDATE_ACCOUNT_FAILED: "UPDATE_ACCOUNT_FAILED",

  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILED: "CHANGE_PASSWORD_FAILED",

  SEARCH_USERS_PAGINATION: "SEARCH_USERS_PAGINATION",
  SEARCH_USERS_PAGINATION_SUCCESS: "SEARCH_USERS_PAGINATION_SUCCESS",
  SEARCH_USERS_PAGINATION_FAILED: "SEARCH_USERS_PAGINATION_FAILED",

  STATISTICAL_USERS: "STATISTICAL_USERS",
  STATISTICAL_USERS_SUCCESS: "STATISTICAL_USERS_SUCCESS",
  STATISTICAL_USERS_FAILED: "STATISTICAL_USERS_FAILED",

  CREATE: "CREATE",
  CREATE_SUCCESS: "CREATE_SUCCESS",
  CREATE_FAILED: "CREATE_FAILED",

  DELETE_USERS: "DELETE_USERS",
  DELETE_USERS_SUCCESS: "DELETE_USERS_SUCCESS",
  DELETE_USERS_FAILED: "DELETE_USERS_FAILED",

  DELETE_USER: "DELETE_USER",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",
}

export default types;