const types = {
  REGISTER: "REGISTER",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILED: "REGISTER_FAILED",

  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",

  LOGIN_WITH_GOOGLE: "LOGIN_WITH_GOOGLE",
  LOGIN_WITH_GOOGLE_SUCCESS: "LOGIN_WITH_GOOGLE_SUCCESS",
  LOGIN_WITH_GOOGLE_FAILED: "LOGIN_WITH_GOOGLE_FAILED",

  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",

  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILED: "FORGOT_PASSWORD_FAILED",

  CHANGE_FORGOT_PASSWORD: "CHANGE_FORGOT_PASSWORD",
  CHANGE_FORGOT_PASSWORD_SUCCESS: "CHANGE_FORGOT_PASSWORD_SUCCESS",
  CHANGE_FORGOT_PASSWORD_FAILED: "CHANGE_FORGOT_PASSWORD_FAILED",

  VERIFY_OTP: "VERIFY_OTP",
  VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
  VERIFY_OTP_FAILED: "VERIFY_OTP_FAILED",

  UPDATE_AUTH: "UPDATE_AUTH",
}

export default types;