const types = {
  GET_ALL_COLORS: "GET_ALL_COLORS",
  GET_ALL_COLORS_SUCCESS: "GET_ALL_COLORS_SUCCESS",
  GET_ALL_COLORS_FAILED: "GET_ALL_COLORS_FAILED",
  
  CREATE_COLOR: "CREATE_COLOR",
  CREATE_COLOR_SUCCESS: "CREATE_COLOR_SUCCESS",
  CREATE_COLOR_FAILED: "CREATE_COLOR_FAILED",

  UPDATE_COLOR: "UPDATE_COLOR",
  UPDATE_COLOR_SUCCESS: "UPDATE_COLOR_SUCCESS",
  UPDATE_COLOR_FAILED: "UPDATE_COLOR_FAILED",

  DELETE_COLOR: "DELETE_COLOR",
  DELETE_COLOR_SUCCESS: "DELETE_COLOR_SUCCESS",
  DELETE_COLOR_FAILED: "DELETE_COLOR_FAILED",
}

export default types;
